// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.196
// </auto-generated>
// ------------------------------------------------------------------------------
namespace ExtensionEssentials
{
    static class Vsix
    {
        public const string Id = "272D01DA-07FC-43BF-ABB0-5B8569FED017";
        public const string Name = "Extension Essentials";
        public const string Description = @"The easiest way to set up Visual Studio for the ultimate development experience. Requires Visual Studio 2017 Update 3 or newer";
        public const string Language = "en-US";
        public const string Version = "1.5";
        public const string Author = "Brad Marshall";
        public const string Tags = "extensions, vsix, install";
    }
}
